nelmio_api_doc:
    documentation:
        info:
            title: Let's Be Busy API
            description: Symfony API for Let's Be Busy application
            version: 0.0.1-dev
    areas: # to filter documented areas
        path_patterns:
            - ^/(issue|project)
